// <auto-generated />
using Chillindo.Core.Models;
using Chillindo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Chillindo.Api.Migrations
{
    [DbContext(typeof(ChillindoContext))]
    [Migration("20180103145413_AccountBalance.RowVersion")]
    partial class AccountBalanceRowVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chillindo.Core.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber");

                    b.Property<bool>("IsActive");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Chillindo.Core.Models.AccountBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountNumber");

                    b.Property<decimal>("Balance");

                    b.Property<string>("Currency");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.ToTable("AccountBalances");
                });

            modelBuilder.Entity("Chillindo.Core.Models.TransactionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountNumber");

                    b.Property<decimal>("Amount");

                    b.Property<string>("Currency");

                    b.Property<DateTime>("TransactionTime");

                    b.Property<int>("TransactionType");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.ToTable("TransactionHistories");
                });

            modelBuilder.Entity("Chillindo.Core.Models.AccountBalance", b =>
                {
                    b.HasOne("Chillindo.Core.Models.Account", "Account")
                        .WithMany("Balances")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Chillindo.Core.Models.TransactionHistory", b =>
                {
                    b.HasOne("Chillindo.Core.Models.Account", "Account")
                        .WithMany("TransactionHistories")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
